name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    permissions: write-all
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: datetime
            asset_name: datetime-linux-amd64
          - os: windows-latest
            artifact_name: datetime.exe
            asset_name: datetime-windows-amd64.exe
          - os: macos-latest
            artifact_name: datetime
            asset_name: datetime-macos-amd64

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
